### PR TITLE
DiagnosisKey: Reject negative retention period for threshold calculation

### PR DESCRIPTION
**Pull request by jonaskoepper**
Hello colleagues,

follow-up on https://github.com/corona-warn-app/cwa-server/pull/211, which was regarding class `DiagnosisKeyService`.

Analogous, this PR improves code in class `DiagnosisKey`:

##### Change type from `long` to `int` for method parameter `daysToRetain` for a method in class `DiagnosisKey`
https://github.com/corona-warn-app/cwa-server/blob/2701e119bcec26a1144616f3ddddcbaedb1baf24/common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java#L140

1. `long` value range not required (current planned retention value in the magnitude of 10 days).
1. The method, as of today, actually crashes with `java.time.DateTimeException` when being called with `Long.MAX` as parameter value (_"Invalid value for EpochDay"..._).

#### For the same method: reject negative values for method parameter `daysToRetain` 
- Negative values not required in the domain; current value range could hide actual errors. 
- See reasoning of  https://github.com/corona-warn-app/cwa-server/pull/211.

### CODE REVIEW

**Comment by jonaskoepper** [comment]
CI build may currently not finish due to https://github.com/corona-warn-app/cwa-server/issues/237.

**Comment by jonaskoepper** [comment]
For the maintainer merging this PR at some point: 
Please delete the auto-generated concatenated commit message from the PR-commits when doing the squash & merge.
The commit title is enough.
Thanks!

**Comment by jonaskoepper** [comment]
@michael-burwig Seems that for some reason the CI build is not always executed when another commit is added to the PR branch.
A result returned for some versions, but the latest is still waiting, for example.

**Comment by michael-burwig** [comment]
@jonaskoepper as far as I am aware, the CircleCI issue is currently on the to-be-investigated list.

**Pull request merged**
