### PR TITLE
Add luca app tracing parameters

### PR DESCRIPTION
**Pull request by ioangut**
## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn -P integration-test clean verify` runs for the whole project and, if you touched any code for a service in the `services` folder, ensure it can be run with `spring-boot:run`

## Description
https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-1209

### CODE REVIEW

**Review by hilmarf — APPROVED** [review]

**Comment by Ein-Tim** [comment]
Hey @ioangut 👋 

Is this change live in PROD already (=One can use the CWA to scan "luca" QR-Codes)? 

Thanks for answering! 
Tim

**Comment by floscher** [comment]
@Ein-Tim Not yet, the latest server release [`2.13.0`](https://github.com/corona-warn-app/cwa-server/releases/tag/v2.13.0) does not contain the change.

But currently the change is on track to be released with the next (server) version in the `2.13.x` series, since it is now in the `release/2.13` branch:
https://github.com/corona-warn-app/cwa-server/blob/be5f3dd3c6e4df485c57a10054c4c136f2d4edf1/services/distribution/src/main/resources/main-config/v2/presence-tracing-parameters.yaml#L122-L126

**Comment by Ein-Tim** [comment]
@floscher 

Thanks for your update. I asked because it could be that the `release/2.13.x` branch was already deployed to the PROD server without merging it into main here or creating a new release.

That's why it would be nice to get feedback from the server team (-:

**Comment by floscher** [comment]
@Ein-Tim At least version `2.13.1` of the Android app from the Play Store currently doesn't recognize the QR codes like this one: https://github.com/corona-warn-app/cwa-documentation/issues/590#issuecomment-829349393

I also don't have insider knowledge and would appreciate an answer from the server team, too. But it looks like we have to wait just a little bit longer.

**Comment by Ein-Tim** [comment]
@floscher 

> At least version 2.13.1 of the Android app from the Play Store currently doesn't recognize the QR codes like this one: https://github.com/corona-warn-app/cwa-documentation/issues/590#issuecomment-829349393

Okay, thanks for the confirmation! Then I guess you're right and this change is not in PROD yet.

I also tried scanning the QR code in https://github.com/corona-warn-app/cwa-documentation/issues/590#issuecomment-829349393 and it doesn't work.

> But it looks like we have to wait just a little bit longer.

Yep. Trying to be patient then 😅

**Comment by ioangut** [comment]
Thank you for looking so close to this topic. We are currently testing it. We will let you know as soon as the deployment will be done in PROD.

**Comment by Ein-Tim** [comment]
Thank you very much @ioangut!

**Comment by DanAmt** [comment]
Does that mean if this is merged CWA can scan any Luca  code ? Or would Luca codes have to be rolled out again ? 
 IMO a very central feature that deserves high prio.

**Comment by Ein-Tim** [comment]
@DanAmt 

Luca QR codes need to be created with the right pattern. See https://github.com/corona-warn-app/cwa-documentation/issues/590#issuecomment-829349393.

**Comment by DanAmt** [comment]
@Ein-Tim So we need the PR in prod and new LUCA codes rolled out for the luca codes to work with CWA . Correct summary ?

**Comment by Ein-Tim** [comment]
@DanAmt 

Luca is already creating compatible QR codes since some months, only the PR needs to be merged and the changes need to be deployed.

**Comment by floscher** [comment]
> Oh well, lets put a shovel on I say. What was the date for Luca to be compatible ? So Luca users can know wether they need to roll out again or not.

Since 26th of May 2021 Luca generates the compatible codes by default. So when a location regenerated their codes after that date, you should be able to check in: https://github.com/corona-warn-app/cwa-documentation/issues/590#issuecomment-848812783

In my experience many locations just never regenerate their codes, so there might still several older codes, but I haven't checked in a while, so this might have improved in the meantime.

**Comment by DanAmt** [comment]
Good , so now we have a clear message:
All luca codes created before 26th of MAY have to be regenerated and the PR needs merging and code push to prod.  Which will happen "soon". 😬

**Comment by Ein-Tim** [comment]
@DanAmt 

You may find https://gitlab.com/lucaapp/android/-/issues/32 & https://gitlab.com/lucaapp/web/-/issues/17 interesting.

**Comment by floscher** [comment]
I was able to successfully checkin to a Luca-Location with the CWA 2.13.2 from the Play Store. :partying_face: So it seems to already be rolled out now.

**Comment by DanAmt** [comment]
The LucaCode needs to be issued after 26. May (date of their changes) , right ?

**Comment by Ein-Tim** [comment]
@DanAmt Yes, correct. See https://www.coronawarn.app/en/faq/#check_in_luca which says:
"QR codes issued as of 25 May 2021 can be read and processed by both the Corona-Warn-App and luca."

**Comment by DanAmt** [comment]
oh, ok, did not see that . To confirm , I was able to check in here: https://github.com/corona-warn-app/cwa-documentation/issues/590#issuecomment-829349393 , which failed yesterday ! Wow, this is so cool !

**Comment by Ein-Tim** [comment]
@floscher 

Just to "proof" what I said in https://github.com/corona-warn-app/cwa-server/pull/1594#issuecomment-959344459, this is now exactly what happened. 
This PR was merged into `release/2.13.x`. However, it was never merged into main (see https://github.com/corona-warn-app/cwa-server/pull/1599) and also there was no new release created. 
So, this repo isn't always reflecting exactly what is deployed and in PROD, that's why I asked.

**Comment by floscher** [comment]
@Ein-Tim There was a release made six days ago: https://github.com/corona-warn-app/cwa-server/releases/tag/v2.13.1 , it's just still marked as pre-release.

So the workflow seems to be to:
* put new commits on the current `release/*` branch
* tag a pre-release on the current `release/*` branch that is tested internally
* when ready, publish the pre-release to production
* then merge the changes into main and upgrade the pre-release to a "full" release

**Comment by Ein-Tim** [comment]
@floscher 

Yes, this seems like what they are doing (but also this behavior was not always the same/consistent over the time). 
I, personally, would expect `main` to reflect what's live in PROD.a

**Comment by ioangut** [comment]
This feature should be in PROD now. We would sync the main branch such that will reflect that also.

**Pull request merged**
