### PR TITLE
Bumps version to 0.3.3

### PR DESCRIPTION
**Pull request by johanneseschrig**

### CODE REVIEW

**Comment by pithumke** [comment]
... and in the dev/int deployments after merging.

**Comment by johanneseschrig** [comment]
@ole-lilienthal I recommend the [files](https://github.com/corona-warn-app/cwa-server/pull/177/files) tab ;)

**Comment by johanneseschrig** [comment]
@pithumke DEV yes, INT will not be affected yet, since it points to `integration`.

**Comment by ole-lilienthal** [comment]
I see, I see, my bad. Infra should be fine without adjustments.

**Pull request merged**
