### PR TITLE
replace size-comparison in test with "hasSameSizeAs"

### PR DESCRIPTION
**Pull request by nils4cosee**
## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description

My SonarLint-plugin displayed this as warning and I just applied the quick-fix.

This is the same as #311, but due to organisational reasons it would have made problems for us to submit a pull request at that time.

### CODE REVIEW

**Comment by stevesap** [comment]
@nils4cosee could you please link to the relevant sonar warning? I'm not seeing it on our https://sonarcloud.io/project/issues?id=corona-warn-app_cwa-server&resolved=false neither was able to find the online reference to it, so I'm curious ;)

**Comment by nils4cosee** [comment]
Oh sorry, I assumed it was SonarLint showing me this warning, but it was actually this plugin: https://github.com/chrisly42/cajon-plugin/blob/master/README.md

**Comment by stevesap** [comment]
@nils4cosee we'd like to merge this in but it seems we are not able to via Github. Can you try perhaps to merge master into your branch manually?

**Comment by nils4cosee** [comment]
@stevesap I have rebased onto the master

**Comment by stevesap** [comment]
@nils4cosee we still cannot merge. Could you please try to check the box 'Allow edits from maintainers' on your PR?

**Pull request merged**
