### PR TITLE
Feature/federation builds

### PR DESCRIPTION
**Pull request by hilmarf**
more and more centrally plugin management...

TODO: fix tests for federation-download

### CODE REVIEW

**Comment by fredrb** [comment]
I'm getting an error when running `mvn clean install` locally on this branch. Apparently because it's trying to run Distribution's Integration Tests, which it shouldn't, because these tests rely on local Object Store. 

```
[ERROR] Errors:
[ERROR]   ObjectStoreAccessIT.defaultIsEmptyTrue » IllegalState Failed to load Applicati...
[ERROR]   ObjectStoreAccessIT.fetchFilesNothingFound » IllegalState Failed to load Appli...
[ERROR]   ObjectStoreAccessIT.pushTestFileAndDelete » IllegalState Failed to load Applic...
[ERROR]   ObjectStoreFilePreservationIT.files_once_published_to_objectstore_should_not_be_overriden_because_of_retention_or_shifting_policies » IllegalState
[ERROR]   S3PublisherIT.publishTestFolderOk » IllegalState Failed to load ApplicationCon...
[INFO]
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0
[INFO]
```

Aren't you getting those also?

**Comment by fredrb** [comment]
Also please check conflicts with `feature/federation`

**Comment by hilmarf** [comment]
> I'm getting an error when running `mvn clean install` locally on this branch. Apparently because it's trying to run Distribution's Integration Tests, which it shouldn't, because these tests rely on local Object Store.
> 
> ```
> [ERROR] Errors:
> [ERROR]   ObjectStoreAccessIT.defaultIsEmptyTrue » IllegalState Failed to load Applicati...
> [ERROR]   ObjectStoreAccessIT.fetchFilesNothingFound » IllegalState Failed to load Appli...
> [ERROR]   ObjectStoreAccessIT.pushTestFileAndDelete » IllegalState Failed to load Applic...
> [ERROR]   ObjectStoreFilePreservationIT.files_once_published_to_objectstore_should_not_be_overriden_because_of_retention_or_shifting_policies » IllegalState
> [ERROR]   S3PublisherIT.publishTestFolderOk » IllegalState Failed to load ApplicationCon...
> [INFO]
> [ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0
> [INFO]
> ```
> 
> Aren't you getting those also?



> I'm getting an error when running `mvn clean install` locally on this branch. Apparently because it's trying to run Distribution's Integration Tests, which it shouldn't, because these tests rely on local Object Store.
> 
> ```
> [ERROR] Errors:
> [ERROR]   ObjectStoreAccessIT.defaultIsEmptyTrue » IllegalState Failed to load Applicati...
> [ERROR]   ObjectStoreAccessIT.fetchFilesNothingFound » IllegalState Failed to load Appli...
> [ERROR]   ObjectStoreAccessIT.pushTestFileAndDelete » IllegalState Failed to load Applic...
> [ERROR]   ObjectStoreFilePreservationIT.files_once_published_to_objectstore_should_not_be_overriden_because_of_retention_or_shifting_policies » IllegalState
> [ERROR]   S3PublisherIT.publishTestFolderOk » IllegalState Failed to load ApplicationCon...
> [INFO]
> [ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0
> [INFO]
> ```
> 
> Aren't you getting those also?

yes, I do, indeed... realized, that the failsafe plugin isn't called at all in normal regular builds - instead it's only used directly within the docker-compose-it

**Review by mibrasap — APPROVED** [review]

**Comment by fredrb** [comment]
Looks good now

**Pull request merged**
