### PR TITLE
Converting properties to yaml

### PR DESCRIPTION
**Pull request by Fobhep**
Solve #245

### CODE REVIEW

**Comment by stevesap** [comment]
closing and reopening to retrigger circle ci

**Comment by stevesap** [comment]
@Fobhep thanks for the contribution!

The Circle CI build is up again - could you please resolve the build issues?

Also, if you could, it would be great if you could do the following 2 changes:
1. normalize all property names to use dashes (some are using underscores) and no camel case
2. update the [README ](https://github.com/corona-warn-app/cwa-server/blob/master/README.md) file to refer to the new yaml file names (there are 3 instances referring to the .properties files)

Thanks!

**Comment by Fobhep** [comment]
@stevesap that should be it - I am not sure the CI actually got triggered.
I will try and close/open it like you did.

Do you want me to squash the commits once this PR is done?

**Comment by stevesap** [comment]
@Fobhep we will re-trigger CI shortly. We use squash and merge strategy by default so you don't need to do it yourself.

**Comment by christian-kirschnick** [comment]
Hey @Fobhep, can you merge master again? Would like to merge this :) Thanks for your contribution!

**Comment by pithumke** [comment]
Please beware, that I add and rename some properties in #183

**Comment by ole-lilienthal** [comment]
Closing this in favour of #277 in which I used the changes provided by @Fobhep but fixed the merge conflicts.

**Comment by Fobhep** [comment]
> Hey @Fobhep, can you merge master again? Would like to merge this :) Thanks for your contribution!

sorry - saw that too late.

**Pull request closed without merging**
