### PR TITLE
reduce version definitions in POMs (rework)

### LINKED ISSUE #302: Reduce version definitions in POMs
We would like to have the feature back from https://github.com/corona-warn-app/cwa-server/pull/265 which externalized the `<version>` 

We had to revert it in https://github.com/corona-warn-app/cwa-server/pull/301 as it was blocking development.

One related issue was https://github.com/corona-warn-app/cwa-server/issues/297

The other (blocking) error when trying to run any of the services was:

```
MINGW64 /c/projects/cwa-server/services/submission (master)
$ mvn spring-boot:run -Dspring-boot.run.fork=false -Dspring-boot.run.profiles=dev -f pom.xml
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< org.opencwa:submission >-----------------------
[INFO] Building submission 0.4.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.3.0.RELEASE:run (default-cli) > test-compile @ submission >>>
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.912 s
[INFO] Finished at: 2020-05-25T16:59:48+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project submission: Could not resolve dependencies for project org.opencwa:submission:jar:0.4.1-SNAPSHOT: Failed to collect dependencies at org.opencwa:persistence:jar:0.4.1-SNAPSHOT -> org.opencwa:protocols:jar:0.4.1-SNAPSHOT: Failed to read artifact descriptor for org.opencwa:protocols:jar:0.4.1-SNAPSHOT: Failure to find org.opencwa:common:pom:${revision} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

### PR DESCRIPTION
**Pull request by CCFenner**
Beside what was done in #265 this PR adds the `flatten-maven-plugin` that resolves the `${revision}` property in the POMs.

### CODE REVIEW

**Comment by stevesap** [comment]
Hi @CCFenner I am still getting the exact same error pasted in https://github.com/corona-warn-app/cwa-server/issues/302#issue-624409833 regardless of whether I run
 
`mvn spring-boot:run -Dspring-boot.run.fork=false -Dspring-boot.run.profiles=dev -f services/submission/pom.xml` 

from the project root or

 `mvn spring-boot:run -Dspring-boot.run.fork=false -Dspring-boot.run.profiles=dev -f pom.xml` 

from 'services/submission'

**Comment by CCFenner** [comment]
Did you do a `mvn clean install` upfront?
I guess this would be a good candidate for an automated test 😄

**Comment by stevesap** [comment]
Thanks @CCFenner I confirmed:
- mvn install works fine on root and all modules
- submission and distribution services execute properly

**Comment by stevesap** [comment]
Hi @CCFenner, could you add the `flatten-maven-plugin` Apache license to the [THIRD-PARTY-NOTICES](https://github.com/corona-warn-app/cwa-server/blob/master/THIRD-PARTY-NOTICES) ?

**Comment by CCFenner** [comment]
@stevesap license added, please review again.

**Pull request merged**
