### PR TITLE
Add missing blanks in warn messages

### PR DESCRIPTION
**Pull request by stweil**
This fixes three alerts reported by LGTM:
https://lgtm.com/projects/g/corona-warn-app/cwa-server/?mode=list

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by michael-burwig** [comment]
Hi @stweil, looks like you (and LGTM) is right here wrt the whitespaces.

On a different note, I remember us putting ``+ "This should never be used in PRODUCTION!"`` deliberately *not* onto new lines for each warn message, but breaking the string at max line width instead. This was because Sonarcloud was complaining about code duplication otherwise and this seemed like the most straightforward fix.

**Comment by stweil** [comment]
Then Sonarcloud should be fixed. Don't write badly formatted code to satisfy buggy tools.

But maybe there is no problem, because Sonarcloud is clever enough to see that it is no code duplication. I'd suggest to simply try it.

**Comment by stevesap** [comment]
I checked locally with SonarLint (due to #237) and it is giving [String literals should not be duplicated](https://rules.sonarsource.com/go/RSPEC-1192#:~:text=Duplicated%20string%20literals%20make%20the,updated%20in%20a%20single%20place.) issue.

Use a string constant instead?

**Comment by pithumke** [comment]
See https://github.com/corona-warn-app/cwa-server/pull/541#discussion_r439301614

**Comment by stweil** [comment]
> I checked locally with SonarLint (due to #237) and it is giving String literals should not be duplicated issue.

As Java is not fully supported by Sonar, I'd disable the test for duplicate string literals.

**Pull request merged**
