### PR TITLE
Refactoring/reformatting in tests

### PR DESCRIPTION
**Pull request by Ra-Jo-cosee**
## Checklist

* [X] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [X] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description

This PR unifies method naming by changing some method names that were written in UpperCamelCase to lowerCamelCase, as well as lowering visibility to private where public isn't needed. lowerCamelCase for method names seems to be the accepted standard in this repository, as it is mentioned in the codestyle linked in CONTRIBUTING.md.
It hopefully also improves readability for a test by extracting out some data generation from the test method, making it more terse.

### CODE REVIEW

**Comment by fredrb** [comment]
Thanks for this PR. At the moment we are planning a big release which will update most of the code in `master` branch. Once that merge is done and any conflicts are fixed, we can review and merge this PR with the proper codebase.

**Comment by fredrb** [comment]
@Ra-Jo-cosee Could you please check the conflicts? We have already done the merge.

**Comment by Ra-Jo-cosee** [comment]
@fredrb The conflicts should be solved.

**Comment by fredrb** [comment]
Since it's a bit difficult to keep this branch up to date with master to fit our merge pipeline, we decided to merge this into a separate branch `community` so we can open the PR ourselves. Thanks for your contribution @Ra-Jo-cosee!

**Pull request merged**
